describe('broken links', () => {
  const brokenLinksTxtFile = 'broken-links.txt';

  it('clear ' + brokenLinksTxtFile, () => {
    cy.writeFile(
      brokenLinksTxtFile,
      '',
    );
  });

  const urls = [
    'https://docs.dnscontrol.org/',
    'https://docs.dnscontrol.org/advanced-features/ci-cd-gitlab',
    'https://docs.dnscontrol.org/advanced-features/cli-variables',
    'https://docs.dnscontrol.org/advanced-features/code-tricks',
    'https://docs.dnscontrol.org/advanced-features/json-reports',
    'https://docs.dnscontrol.org/advanced-features/nameservers',
    'https://docs.dnscontrol.org/advanced-features/notifications',
    'https://docs.dnscontrol.org/commands/check-creds',
    'https://docs.dnscontrol.org/commands/creds-json',
    'https://docs.dnscontrol.org/commands/get-certs',
    'https://docs.dnscontrol.org/commands/get-zones',
    'https://docs.dnscontrol.org/developer-info/adding-new-rtypes',
    'https://docs.dnscontrol.org/developer-info/alias',
    'https://docs.dnscontrol.org/developer-info/bug-triage',
    'https://docs.dnscontrol.org/developer-info/byo-secrets',
    'https://docs.dnscontrol.org/developer-info/debugging-with-dlv',
    'https://docs.dnscontrol.org/developer-info/integration-tests',
    'https://docs.dnscontrol.org/developer-info/opinions',
    'https://docs.dnscontrol.org/developer-info/ordering',
    'https://docs.dnscontrol.org/developer-info/styleguide-code',
    'https://docs.dnscontrol.org/developer-info/styleguide-doc',
    'https://docs.dnscontrol.org/developer-info/testing-txt-records',
    'https://docs.dnscontrol.org/developer-info/unittests',
    'https://docs.dnscontrol.org/developer-info/writing-providers',
    'https://docs.dnscontrol.org/getting-started/colors',
    'https://docs.dnscontrol.org/getting-started/examples',
    'https://docs.dnscontrol.org/getting-started/getting-started',
    'https://docs.dnscontrol.org/getting-started/migrating',
    'https://docs.dnscontrol.org/getting-started/typescript',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/a',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/aaaa',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/alias',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/autodnssec_off',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/autodnssec_on',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/caa',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/caa_builder',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/cname',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/defaultttl',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/dhcid',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/disable_ignore_safety_check',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/dmarc_builder',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/dnsprovider',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/ds',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/frame',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/ignore',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/ignore_name',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/ignore_target',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/import_transform',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/include',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/loc',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/loc_builder_dd',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/loc_builder_dmm_str',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/loc_builder_dms_str',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/loc_builder_str',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/m365_builder',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/mx',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/nameserver',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/nameserver_ttl',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/naptr',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/no_purge',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/ns',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/ptr',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/purge',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/service-provider-specific',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/soa',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/spf_builder',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/srv',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/sshfp',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/tlsa',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/txt',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/url',
    'https://docs.dnscontrol.org/language-reference/domain-modifiers/url301',
    'https://docs.dnscontrol.org/language-reference/js',
    'https://docs.dnscontrol.org/language-reference/record-modifiers',
    'https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific',
    'https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific/amazon-route-53',
    'https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific/amazon-route-53/r53_evaluate_target_health',
    'https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific/amazon-route-53/r53_zone',
    'https://docs.dnscontrol.org/language-reference/record-modifiers/ttl',
    'https://docs.dnscontrol.org/language-reference/top-level-functions',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/d',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/defaults',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/domain_elsewhere',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/domain_elsewhere_auto',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/d_extend',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/fetch',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/getconfigureddomains',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/ip',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/newdnsprovider',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/newregistrar',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/panic',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/require',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/require_glob',
    'https://docs.dnscontrol.org/language-reference/top-level-functions/rev',
    'https://docs.dnscontrol.org/language-reference/why-the-dot',
    'https://docs.dnscontrol.org/release/release-engineering',
    'https://docs.dnscontrol.org/release/v316',
    'https://docs.dnscontrol.org/service-providers/providers',
    'https://docs.dnscontrol.org/service-providers/providers/akamaiedgedns',
    'https://docs.dnscontrol.org/service-providers/providers/autodns',
    'https://docs.dnscontrol.org/service-providers/providers/axfrddns',
    'https://docs.dnscontrol.org/service-providers/providers/azure_dns',
    'https://docs.dnscontrol.org/service-providers/providers/azure_private_dns',
    'https://docs.dnscontrol.org/service-providers/providers/bind',
    'https://docs.dnscontrol.org/service-providers/providers/bunny_dns',
    'https://docs.dnscontrol.org/service-providers/providers/cloudflareapi',
    'https://docs.dnscontrol.org/service-providers/providers/cloudns',
    'https://docs.dnscontrol.org/service-providers/providers/cscglobal',
    'https://docs.dnscontrol.org/service-providers/providers/desec',
    'https://docs.dnscontrol.org/service-providers/providers/digitalocean',
    'https://docs.dnscontrol.org/service-providers/providers/dnsimple',
    'https://docs.dnscontrol.org/service-providers/providers/dnsmadeeasy',
    'https://docs.dnscontrol.org/service-providers/providers/dnsoverhttps',
    'https://docs.dnscontrol.org/service-providers/providers/domainnameshop',
    'https://docs.dnscontrol.org/service-providers/providers/dynadot',
    'https://docs.dnscontrol.org/service-providers/providers/easyname',
    'https://docs.dnscontrol.org/service-providers/providers/exoscale',
    'https://docs.dnscontrol.org/service-providers/providers/gandi_v5',
    'https://docs.dnscontrol.org/service-providers/providers/gcloud',
    'https://docs.dnscontrol.org/service-providers/providers/gcore',
    'https://docs.dnscontrol.org/service-providers/providers/hedns',
    'https://docs.dnscontrol.org/service-providers/providers/hetzner',
    'https://docs.dnscontrol.org/service-providers/providers/hexonet',
    'https://docs.dnscontrol.org/service-providers/providers/hostingde',
    'https://docs.dnscontrol.org/service-providers/providers/internetbs',
    'https://docs.dnscontrol.org/service-providers/providers/inwx',
    'https://docs.dnscontrol.org/service-providers/providers/linode',
    'https://docs.dnscontrol.org/service-providers/providers/loopia',
    'https://docs.dnscontrol.org/service-providers/providers/luadns',
    'https://docs.dnscontrol.org/service-providers/providers/msdns',
    'https://docs.dnscontrol.org/service-providers/providers/mythicbeasts',
    'https://docs.dnscontrol.org/service-providers/providers/namecheap',
    'https://docs.dnscontrol.org/service-providers/providers/namedotcom',
    'https://docs.dnscontrol.org/service-providers/providers/netcup',
    'https://docs.dnscontrol.org/service-providers/providers/netlify',
    'https://docs.dnscontrol.org/service-providers/providers/ns1',
    'https://docs.dnscontrol.org/service-providers/providers/opensrs',
    'https://docs.dnscontrol.org/service-providers/providers/oracle',
    'https://docs.dnscontrol.org/service-providers/providers/ovh',
    'https://docs.dnscontrol.org/service-providers/providers/packetframe',
    'https://docs.dnscontrol.org/service-providers/providers/porkbun',
    'https://docs.dnscontrol.org/service-providers/providers/powerdns',
    'https://docs.dnscontrol.org/service-providers/providers/realtimeregister',
    'https://docs.dnscontrol.org/service-providers/providers/route53',
    'https://docs.dnscontrol.org/service-providers/providers/rwth',
    'https://docs.dnscontrol.org/service-providers/providers/softlayer',
    'https://docs.dnscontrol.org/service-providers/providers/transip',
    'https://docs.dnscontrol.org/service-providers/providers/vultr',
  ];

  const knownIssue = [
    'https://github.com/StackExchange/dnscontrol/settings/secrets/actions',
    'https://gitlab.com/cafferata/dnscontrol/-/pipelines/new',
    'https://github.com/StackExchange/dnscontrol/blob/master/docs/assets/1password/creds.json',
    'https://github.com/StackExchange/dnscontrol/blob/master/docs/assets/getting-started/creds.json',
    'https://github.com/StackExchange/dnscontrol/blob/master/docs/assets/getting-started/dnsconfig.js',
    'https://github.com/StackExchange/dnscontrol/blob/master/docs/providers.md',
    'https://github.com/StackExchange/dnscontrol/blob/master/docs/writing-providers.md',
  ];
  for (const url of urls) {
    it('find all broken links in de content of ' + url, () => {
      cy.visit(url);
      cy.get('main a').each(link => {
        if (link.prop('href'))
          cy.request({
            url: link.prop('href'),
            failOnStatusCode: false,
          }).then(
            (response) => {
              if (response.status === 404) {
                if (knownIssue.includes(link.prop('href'))) return;

                cy.writeFile(
                  brokenLinksTxtFile,
                  url + '\n- ' + link.prop('href') + '\n',
                  {
                    flag: 'a+',
                  },
                );
              }
            },
          );
      });
    });
  }
});
